### ISSUE TITLE
bedhost config file location

### ISSUE THREAD

**Issue by nsheff** [databio/bedhost#24]
Right now it appears there's only 1 config option for where files are stored on disk. It's a bit confusing to me that the bedbuncher pipeline is sticking its results into the same output folder as bedstat.

demo config looks like:

```
path:
  pipelines_output: $BEDBASEtutorial/bedstat/bedstat_output

database:
  host: localhost
  bed_index: bed_index
  bedset_index: bedset_index

server:
  host: 0.0.0.0
  port: 8000
```

Instead, I propose:
```
path:
  bedstat_output: $BEDBASEtutorial/bedstat_output
  bedbuncher_output: $BEDBASEtutorial/bedbuncher
```

This maintains the modularity of the bed files vs bedsets.
